# Generated by Django 5.1.1 on 2024-10-07 21:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("receitas", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita",
            old_name="tempo_de_preparo",
            new_name="tempo_preparo",
        ),
        migrations.AlterField(
            model_name="receita",
            name="data_receita",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
