# Generated by Django 5.1.1 on 2024-10-07 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("receitas", "0002_rename_tempo_de_preparo_receita_tempo_preparo_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="receita",
            old_name="modo_de_preparo",
            new_name="modo_preparo",
        ),
    ]
