# Generated by Django 5.1.1 on 2024-10-08 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pessoas", "0001_initial"),
        ("receitas", "0003_rename_modo_de_preparo_receita_modo_preparo"),
    ]

    operations = [
        migrations.AddField(
            model_name="receita",
            name="pessoa",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="pessoas.pessoa",
            ),
        ),
    ]
